[ui]
hideTopBar = true
layout = "wide"

[theme]
# Base theme (will be overridden by our custom theming system)
base = "light"
primaryColor = "#4C78AF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans-serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501